name: MacOS application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleFoundationTests"
        run: xcodebuild test -project NeedleFoundation.xcodeproj -scheme NeedleFoundation -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11'
      - name: "NeedleGeneratorTests"
        run: cd Generator && swift test -Xswiftc -DDEBUG
      - name: "NeedleGeneratorBinary"
        run: cd Generator && swift build -c release
      - name: "NeedleSampleMVCApp"
        run: xcodebuild build -project Sample/MVC/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToe -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11'
      - name: "NeedleSampleMVCTests"
        run: xcodebuild test -project Sample/MVC/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToeTests -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11'
      - name: "NeedleSamplePluginizedApp"
        run: xcodebuild build -project Sample/Pluginized/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToe -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11'
      - name: "NeedleSamplePluginizedScoreSheetTests"
        run: xcodebuild test -project Sample/Pluginized/TicTacToe/TicTacToe.xcodeproj -scheme ScoreSheetTests -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11'
      - name: "NeedleSamplePluginizedTicTacToeCoreTests"
        run: xcodebuild test -project Sample/Pluginized/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToeCoreTests -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11'
